[project]
name = "palm-postproc-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "netcdf4>=1.7.2",
    "numpy>=2.3.1",
]
